## Numpy Odev

1-Numpy kütüphanesini import edin.

In [1]:
# 1
import numpy as np

2-1'den 5 e kadar (5 dahil) b isimli bir dizi oluşturun.

In [2]:
# 2
b = np.array(range(1,6))
b

array([1, 2, 3, 4, 5])

3- 20 adet 0'dan oluşan 4 x 5' lik dizi oluşturun.

In [3]:
# 3
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

4- 15 adet 7 sayısından oluşan diziyi 3x5 olarak yazın.

In [4]:
# 4
np.full((3,5), 7)

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

5- 10–70 e kadar 5 er artan sayıları yaz.

In [5]:
# 5
np.arange(10,70,5)

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65])

6- 10–20 arasında 15 aynı uzaklıkta elemanı olan array oluşturun. (linspace metodunu kullanın.)

In [6]:
# 6
np.linspace(10,20,15)

array([10.        , 10.71428571, 11.42857143, 12.14285714, 12.85714286,
       13.57142857, 14.28571429, 15.        , 15.71428571, 16.42857143,
       17.14285714, 17.85714286, 18.57142857, 19.28571429, 20.        ])

7- Rastgele sayılardan oluşan diziyi 3x5 boyutunda yazdır.

In [7]:
# 7
np.random.randint(1, 50, (3,5))

array([[43,  2, 33,  1, 21],
       [18, 32, 33, 17, 30],
       [32, 34,  7, 30,  7]])

8- 5 elemanlı birim matris oluşturun. eye() metodu kullanın.

In [8]:
# 8
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

9- 0'dan 24 e kadar array oluştur. Sonra reshape metodu ile 4x6 boyutu olarak yazın.

In [9]:
# 9
a = np.arange(0,24)
a.reshape((4,6))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

10- 0 ile 1 arasında rastgele 10 sayıdan oluşan bir array tanımlayın. Minimum ve maksimum değerleri bulun.

In [10]:
# 10
a = np.random.uniform(0,1,10)
print("Arrayin max değeri : {}".format(a.max()))
print("Arrayin min değeri : {}".format(a.min()))

Arrayin max değeri : 0.849181272556896
Arrayin min değeri : 0.04158175995702251


11- 36 sayıdan oluşan rastgele sayılar 6x6' lık array olarak yazdırın.

In [11]:
# 11
a = np.random.randint(0,100,(6,6))
a

array([[13, 45, 60, 29, 49, 43],
       [35, 15, 24, 75,  2, 45],
       [98, 34, 12, 60, 78, 10],
       [49, 96, 92, 54, 62, 76],
       [31, 52,  3, 98, 96,  5],
       [49, 58, 84, 55, 62, 40]])

12- 5.satırdaki elemanları gösteriniz.

In [12]:
# 12 
a[4,:]

array([31, 52,  3, 98, 96,  5])

13- 6.satır ve 6.sutundaki elemanları gösteriniz.

In [13]:
# 13
print(a[5])
print(a[:,[5]])

[49 58 84 55 62 40]
[[43]
 [45]
 [10]
 [76]
 [ 5]
 [40]]


14-4.sutundaki tüm elemanları çekin.

In [14]:
# 14
a[:,[3]]

array([[29],
       [75],
       [60],
       [54],
       [98],
       [55]])

15- For döngüsünü ve flat metodunu kullanarak satır satır elemanları yazdırınız.

In [15]:
# 15
for j, i in enumerate(range(0,36,6)):
    print("{}. satır: {}".format(j+1 ,a.flat[i:i+6]))
    

1. satır: [13 45 60 29 49 43]
2. satır: [35 15 24 75  2 45]
3. satır: [98 34 12 60 78 10]
4. satır: [49 96 92 54 62 76]
5. satır: [31 52  3 98 96  5]
6. satır: [49 58 84 55 62 40]


16- 0 ile 1 aralığında bir array oluştur. Bu array değerini 5 ile çarpın.

In [16]:
# 16
arr = np.random.uniform(0,1,6)
arr = np.multiply(arr, 2)
arr

array([0.41442046, 0.00972325, 1.97920681, 0.14537176, 0.16744099,
       1.91349548])

17- Satırların toplam değeri nedir?

In [17]:
# 17
np.sum(arr)

4.629658750142294

18-Satırların standart sapma değeri nedir?

In [18]:
# 18
np.std(arr)

0.8393889446357483

19-Satırların varyans değeri nedir?

In [19]:
# 19
np.var(arr)

0.7045738003767154

20- Satırların transpoz değeri nedir?

In [20]:
# 20
arr.T

array([0.41442046, 0.00972325, 1.97920681, 0.14537176, 0.16744099,
       1.91349548])